version: '3'
services:

  redis-sentinel1:
    image: lgatica/redis-sentinel:4.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - CLIENTHOST=192.168.137.101
      - CLIENTPORT=26379
      - MASTERHOST=192.168.137.101
      - MASTERPORT=6379
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
      - REQUIREPASS=password1234
    volumes:
      - "../sentinel-data/sentinel1:/redis"
    restart: always

  redis-sentinel2:
    image: lgatica/redis-sentinel:4.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - CLIENTHOST=192.168.137.101
      - CLIENTPORT=26380
      - MASTERHOST=192.168.137.101
      - MASTERPORT=6379
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
      - REQUIREPASS=password1234
    volumes:
      - "../sentinel-data/sentinel2:/redis"
    restart: always

  redis-sentinel3:
    image: lgatica/redis-sentinel:4.0.2
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: "host"
    environment:
      - CLIENTHOST=192.168.137.101
      - CLIENTPORT=26381
      - MASTERHOST=192.168.137.101
      - MASTERPORT=6379
      - QUORUM=2
      - DOWN_AFTER_MILLISEC=5000
      - FAILOVER_TIMEOUT=30000
      - REQUIREPASS=password1234
    volumes:
      - "../sentinel-data/sentinel3:/redis"
    restart: always